/*
 * Copyright 2026 Flix Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

///
/// The `Extras` module is a collection of submodules that extend the official
/// Flix library, each offering a self-contained piece of functionality:
///
/// - `Extras.Graph` is a library of functions on directed graphs represented
///   as collections of edges.
/// - `Extras.Queue` is an immutable first-in, first-out queue.
///
pub mod Extras {
    /* empty */
}
